### ISSUE TITLE
PA Review: User Auth

### ISSUE THREAD

**Issue by M3L6H** [M3L6H/Turmoil#23]
**ToDo**

- [x] Backend: DB, model, controller, views

- [x] Redux Loop: ajax, actions, reducer

- [x] Presentational Components

- [x] Styling

- [x] Smooth, bug-free navigation

- [x] Adequate and appropriate seeds

**Comment by M3L6H** [comment]
Everything should be done except for seeds. I will add some nice user seeds tomorrow.

**Comment by M3L6H** [comment]
Added seeds with 1d449add126846b36031088d0d30fdc19bd77d08.

**Comment by M3L6H** [comment]
Added demo user with 09dfdc131ef30151fdef1ed640d38e001a2c270c
