### ISSUE TITLE
Realms don't have to be in a cluster

### ISSUE THREAD

**Issue by M3L6H** [M3L6H/Turmoil#50]
**ToDo**

- [x] Update realms table so cluster_id is not required

- [x] Update realms table to include a required dimension_id column

- [x] Update realm validations

- [x] Update dimension associations

- [x] Update realm associations

**Comment by M3L6H** [comment]
Updated realms table in 7eec7ac6231b4d0a44abffac8807a4dec0879679

**Comment by M3L6H** [comment]
Updated realm and dimension models in d439a728aa75654cfc2eb3c5e8b2d62697ba1264
